http:
  port: 8080
apiEndpoints:
  plans-service:
    host: "*"
    paths: ["/api/plans/*", "/api/plans"]
  subscriptions-service:
    host: "*"
    paths: ["/api/subscriptions/*", "/api/subscriptions"]
serviceEndpoints:
  plans-service-endpoint:
    url: "http://localhost:3001/"
  subscriptions-service-endpoint:
    url: "http://localhost:3002/"
policies:
  # - basic-auth
  # - cors
  # - expression
  # - key-auth
  # - log
  # - oauth2
  - proxy
  # - rate-limit
pipelines:
  plans-service-pipeline:
    apiEndpoints:
      - plans-service
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: plans-service-endpoint
              changeOrigin: true # localhost:8080 -> localhost:3001
              stripPath: true # localhost:8080/api/plans -> localhost:3001(/api/plans -> removed)
  subscriptions-service-pipeline:
    apiEndpoints:
      - subscriptions-service
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: subscriptions-service-endpoint
              changeOrigin: true # localhost:8080 -> localhost:3001
              stripPath: true # localhost:8080/api/plans -> localhost:3001(/api/plans -> removed)